{{- if .Values.query.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "loglake.componentName" (list . "query") }}
  labels:
    {{- include "loglake.componentLabels" (list . "query") | nindent 4 }}
    loglake.limnion.ai/scrape: "true"
spec:
  type: ClusterIP
  selector:
    {{- include "loglake.componentSelectorLabels" (list . "query") | nindent 4 }}
  ports:
    - name: http
      port: 8089
      targetPort: http
      protocol: TCP
    - name: metrics
      port: 9105
      targetPort: metrics
      protocol: TCP
{{- end }}
