[workspace]
resolver = "2"
members = [
    "adapter",
    "baseline",
    "candidate/iceberg",
    "candidate/iceberg-catalog-sql",
    "candidate/iceberg-storage-opendal",
]

[workspace.package]
edition = "2024"
rust-version = "1.94"
license = "Apache-2.0"

[patch.crates-io]
iceberg = { path = "candidate/iceberg" }
iceberg-catalog-sql = { path = "candidate/iceberg-catalog-sql" }
iceberg-storage-opendal = { path = "candidate/iceberg-storage-opendal" }
